ALTER TABLE user_vocab_stats
ADD COLUMN IF NOT EXISTS current_set INT DEFAULT 1,
ADD COLUMN IF NOT EXISTS sets_completed INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS highest_set_unlocked INT DEFAULT 1,
ADD COLUMN IF NOT EXISTS experience_points INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_words_mastered INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS words_mastered INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS streak_days INT DEFAULT 0;
